### ISSUE TITLE
Jellyfin Not Finding Some Posters

### ISSUE THREAD

**Issue by Entree3k** [Entree3k/Jellyfin#3]
Jellyfin is having issues not finding the posters for;
FUNimation Entertainment
Sky Atlantic (UK)
Sky Deutschland
TV Aichi
TV2 (NZ)
YTV (CA)

**Comment by Entree3k** [comment]
Fixed Funimation and Sky Deutschland

**Comment by SenorSmartyPants** [comment]
TV2 (NZ) needs to be added to thumbs.txt

**Comment by Entree3k** [comment]
TV2 NZ is working now as well as Sky Deutschland

**Comment by LeviSnoot** [comment]
Adding to the list, the following are not found by my instance:

- ABC (US)
- TV Aichi

I attempted restarting Jellyfin as insructed in #11, however this did not fix it.

**Comment by LeviSnoot** [comment]
I just created PR #12 which will hopefully fix both this and #11.

**Comment by Entree3k** [comment]
I merged the pull request so let's see if this issue gets resolved.

**Comment by LeviSnoot** [comment]
Doesn't look like this fixed it unfortunately, but as I'm taking a look at the [original Jellyfin Artwork Repository](https://github.com/jellyfin/jellyfin-artwork) I see that they are using [JSON files](https://github.com/jellyfin/jellyfin-artwork/blob/master/studios/hbo/studio.json) to identify the studios. This makes a lot more sense to me as it can uses some better identifiers such as IMDb ID's etc.

I think the best bet for making this repo work is to adopt that structure here. 

The way I would do this is forking the Jellyfin repo, and then re-implementing the artwork that already exists in this repo one by one. Lots of work, but necessary for this repo to work. What do you think @Entree3k?

**Comment by Entree3k** [comment]
I mean I don't think it would be that much work. I can pull all the data from the Jellyfin Artwork Repo, the JSON files are already written up for the networks. We can just migrate images over to that. I see the JSON files are using .svg files for the images so I can just bulk convert all the jpg -> svg.

**Comment by AsHalt** [comment]
Just wondering if the project's still alive... 

--------

might need more Japanese studio image/ posters. Lots of default text

**Comment by Entree3k** [comment]
What networks are missing? I've been a little busy lately so this project is all community driven if anyone wants to make contributions feel free to add your posters for the networks and create a pull request.

**Comment by AsHalt** [comment]
Using _Shoko server*_ , so it adds lots metadata in to the studio/ TV network.

So should I dump it one by one or by the whole bunch, should I do the pull request? (there's at least 20+)

\---

- NagoyaTV
- NHK /NHK (JP)
- Nexus
- MBS (JP) (extra metadata)
- MadHouse
- J.C.Staff
- ENGI 
- Clover Works
- ... (.etc)

![Image](https://github.com/user-attachments/assets/44a95e51-45f9-404a-a5ae-4356fe80c974)

![Image](https://github.com/user-attachments/assets/db24a865-44eb-405d-aeeb-37c0a22e8bb1)

![Image](https://github.com/user-attachments/assets/8c9fedbb-5873-4ca4-9d22-0fef324166f6)

( ^ not the complete list of studios/ networks )

\---

\* [Shoko Server](https://github.com/ShokoAnime/ShokoServer) uses data from AniDB (Primary), and TMDB

**Comment by Entree3k** [comment]
It's odd it's not even showing Apple TV, HBO Max and Disney+ since they pull up for me. If you would like to help I'd appreciate it. Just fork the repo, add the posters for the networks so they match the style of the repo and create a pull request.
